[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  PNPM_VERSION = "9"

[functions]
  node_bundler = "esbuild"
  included_files = ["src/**"]

[[redirects]]
  from = "/api/admin/orders"
  to   = "/.netlify/functions/admin-orders"
  status = 200

[[redirects]]
  from = "/api/admin/orders/:id"
  to   = "/.netlify/functions/admin-order?id=:id"
  status = 200

# PayFast payment integration
[[redirects]]
  from = "/api/payfast/checkout"
  to   = "/.netlify/functions/payfast-checkout"
  status = 200

[[redirects]]
  from = "/api/payfast/itn"
  to   = "/.netlify/functions/payfast-itn"
  status = 200

[[redirects]]
  from = "/api/orders/create"
  to   = "/.netlify/functions/create-order"
  status = 200

# SPA catch-all: redirect all non-file requests to index.html
[[redirects]]
  from = "/*"
  to   = "/index.html"
  status = 200
