[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

# Single Page App routing (React Router / Vite)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes – never hijack function requests
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
