export const config = { 
  business: { 
    name: "Madiega Trading Enterprise", 
    tagline: "Solar. Electrical. Plumbing. Construction. Security.", 
    sub: "Professional installations and supplies across Gauteng.", 
    phone: "+27 63 296 2738", 
    whatsapp: "27632962738", 
    email: "info@madiegafurniture.co.za", 
    address: "6 Pretorius Road, Henley-on-Klip, Meyerton, 1962", 
    address2: "148 Columbine Avenue, Mondeor, Johannesburg South", 
    calloutFee: "R450", 
    established: "2020", 
    coverage: "Gauteng — Vaal Triangle, JHB South, Meyerton", 
    heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1600", 
    mapsEmbed: "https://maps.google.com/maps?q=Henley+on+Klip&output=embed", 
  }, 
  stats: [ 
    { value: "500+", label: "Projects Completed" }, 
    { value: "5+", label: "Years Experience" }, 
    { value: "2", label: "Gauteng Locations" }, 
    { value: "24hr", label: "Response Time" }, 
  ], 
  trust: [ 
    { icon: "award", label: "Qualified Installers" }, 
    { icon: "file-check", label: "COC Certificates Issued" }, 
    { icon: "map-pin", label: "Gauteng-Wide Coverage" }, 
    { icon: "shield-check", label: "1-Year Workmanship Warranty" }, 
  ], 
  services: [ 
    { 
      id: "solar-electrical", 
      name: "Solar & Electrical", 
      slug: "/services/solar-electrical", 
      icon: "sun", 
      tagline: "Stop paying Eskom. Start owning your power.", 
      heroImage: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=1200", 
      intro: "Full solar system design, supply, and professional installation for homes and businesses across Gauteng. We supply and install MPPT inverters, lithium batteries, solar panels, and complete backup systems — with COC certificates included.", 
      solutions: [ 
        { 
          name: "5KW Backup System", 
          description: "Complete inverter + lithium battery backup system. Powers your home through loadshedding without solar panels.", 
          price: "From R18,500 installed", 
          image: "https://images.unsplash.com/photo-1593941707882-a5bac6861d5d?w=600", 
        }, 
        { 
          name: "Full Solar System", 
          description: "Panels + inverter + batteries — reduce your Eskom bill by up to 80%. Tailored to your home's usage.", 
          price: "From R35,000 installed", 
          image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600", 
        }, 
        { 
          name: "Electrical Callouts", 
          description: "Residential and commercial electrical work — DB boards, COC certificates, fault finding, additional points.", 
          price: "Callout fee: R450", 
          image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600", 
        }, 
      ], 
      features: [ 
        "5KW & 5.5KW MPPT 100A WiFi inverter installations", 
        "Lithium battery storage systems", 
        "Solar panel supply and installation", 
        "Municipal grid-tie and hybrid systems", 
        "DB board upgrades and COC certificates", 
        "Fault finding and electrical repairs", 
        "WiFi monitoring app included", 
      ], 
      process: [ 
        { step: "1", title: "Free Site Assessment", desc: "We visit your property, assess your usage, and recommend the right system." }, 
        { step: "2", title: "Tailored Quote", desc: "You receive a detailed quote within 24 hours — no hidden fees." }, 
        { step: "3", title: "Professional Install", desc: "Our qualified team installs your system cleanly and efficiently." }, 
        { step: "4", title: "COC & Handover", desc: "Certificate of Compliance issued. We walk you through the system." }, 
      ], 
      callout: "Callout fee: R450 — credited toward job cost", 
      cta: "Get a Solar Quote", 
    }, 
    { 
      id: "plumbing", 
      name: "Plumbing", 
      slug: "/services/plumbing", 
      icon: "droplets", 
      tagline: "Never run out of water again.", 
      heroImage: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=1200", 
      intro: "Professional plumbing services for residential and commercial properties across Gauteng. From emergency leak repairs to full municipal water backup installations — we respond fast and fix it right.", 
      solutions: [ 
        { 
          name: "Municipal Water Backup", 
          description: "Complete water backup system with filtration. Never affected by municipal water outages again.", 
          price: "From R3,999 installed", 
          image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600", 
        }, 
        { 
          name: "5000L Water Tank System", 
          description: "Full water independence — 5000L tank, pump, filter, and professional installation included.", 
          price: "From R25,899 installed", 
          image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600", 
        }, 
        { 
          name: "Geyser & Solar Geyser", 
          description: "Geyser replacements, Geyserwise controllers, and solar geyser installations.", 
          price: "From R4,500 installed", 
          image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600", 
        }, 
      ], 
      features: [ 
        "Municipal water backup installations", 
        "5000L water tank systems", 
        "Leak detection and repairs", 
        "Geyser replacements", 
        "Solar geyser installations", 
        "Drain cleaning and blockages", 
        "Pipe installations and rerouting", 
        "Kitchen and bathroom renovations", 
      ], 
      process: [ 
        { step: "1", title: "Book a Callout", desc: "Call or WhatsApp us — we confirm your appointment same day." }, 
        { step: "2", title: "Assessment & Quote", desc: "Our plumber assesses the job and gives you a clear quote on the spot." }, 
        { step: "3", title: "Fix It Right", desc: "Professional repair or installation — we don't leave until it's done." }, 
        { step: "4", title: "Clean Site", desc: "We clean up after ourselves. Every time." }, 
      ], 
      callout: "Callout fee: R450 — credited toward job cost", 
      cta: "Book a Plumber", 
    }, 
    { 
      id: "construction", 
      name: "Construction", 
      slug: "/services/construction", 
      icon: "hard-hat", 
      tagline: "Built right. Built to last.", 
      heroImage: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=1200", 
      intro: "Quality construction services for residential and commercial properties across Gauteng. From small renovations to full additions — we deliver professional results on time and within budget.", 
      solutions: [ 
        { 
          name: "Renovations & Additions", 
          description: "Extensions, additional rooms, garage conversions, and full home renovations.", 
          price: "Get a free site assessment", 
          image: "https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=600", 
        }, 
        { 
          name: "Tiling & Plastering", 
          description: "Professional tiling, plastering, and finishing work for floors, walls, and outdoor surfaces.", 
          price: "Get a free quote", 
          image: "https://images.unsplash.com/photo-1571171637578-41bc2dd41cd2?w=600", 
        }, 
        { 
          name: "Paving & Outdoor", 
          description: "Driveways, patios, paths, and garden paving using quality materials.", 
          price: "Get a free quote", 
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600", 
        }, 
      ], 
      features: [ 
        "Residential renovations and additions", 
        "Brickwork and blockwork", 
        "Plastering and skimming", 
        "Floor and wall tiling", 
        "Paving and outdoor surfaces", 
        "Roofing repairs and installations", 
        "Drywall and ceiling installations", 
        "Free site assessment available", 
      ], 
      process: [ 
        { step: "1", title: "Free Site Visit", desc: "We come to you, assess the project, and understand exactly what you need." }, 
        { step: "2", title: "Detailed Quote", desc: "Full written quote with materials and labour — no surprises." }, 
        { step: "3", title: "Scheduled Build", desc: "We agree on a start date and timeline. We stick to it." }, 
        { step: "4", title: "Quality Handover", desc: "Final inspection with you before we consider the job done." }, 
      ], 
      callout: "Free site assessment — no obligation", 
      cta: "Request Assessment", 
    }, 
    { 
      id: "security", 
      name: "Security Solutions", 
      slug: "/services/security", 
      icon: "shield", 
      tagline: "Protect what matters most.", 
      heroImage: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=1200", 
      intro: "Professional security system supply and installation for homes and businesses. We assess your property, recommend the right solution, and install it cleanly — with full handover and support.", 
      solutions: [ 
        { 
          name: "CCTV Systems", 
          description: "HD cameras, DVR/NVR recording, remote phone viewing, and professional installation.", 
          price: "From R5,500 installed", 
          image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600", 
        }, 
        { 
          name: "Electric Fencing", 
          description: "Energiser, wire, and professional installation for standard residential or commercial plots.", 
          price: "From R4,800 installed", 
          image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600", 
        }, 
        { 
          name: "Alarm Systems", 
          description: "Full alarm system with sensors, siren, keypad, and optional armed response connection.", 
          price: "From R3,500 installed", 
          image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600", 
        }, 
      ], 
      features: [ 
        "HD CCTV camera systems", 
        "Electric fence installations", 
        "Alarm systems and sensors", 
        "Access control and intercoms", 
        "Security lighting", 
        "Remote phone monitoring", 
        "Free security assessment", 
      ], 
      process: [ 
        { step: "1", title: "Free Assessment", desc: "We visit your property and identify vulnerabilities and the right solution." }, 
        { step: "2", title: "Custom Quote", desc: "Tailored quote based on your property and security needs." }, 
        { step: "3", title: "Clean Install", desc: "Professional installation — neat cable routing, no mess." }, 
        { step: "4", title: "Full Handover", desc: "We show you how everything works and set up remote access on your phone." }, 
      ], 
      callout: "Free security assessment — no obligation", 
      cta: "Get a Security Quote", 
    }, 
  ], 
  products: [ 
    { id: 1, name: "5.5KW MPPT 100A WiFi Inverter", category: "Solar", price: 12299, description: "Hybrid MPPT solar inverter with WiFi app monitoring. Suits 3-bed homes.", image: "https://images.unsplash.com/photo-1593941707882-a5bac6861d5d?w=600", badge: "Best Seller" }, 
    { id: 2, name: "100Ah Lithium Battery", category: "Solar", price: 8900, description: "Deep cycle lithium — compatible with all major hybrid inverters.", image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600" }, 
    { id: 3, name: "Municipal Water Backup System", category: "Plumbing", price: 3999, description: "Complete water backup with filter. Installation included.", image: "https://images.unsplash.com/photo-1504328345606-18bbc8c9d7d1?w=600", badge: "Popular" }, 
    { id: 4, name: "5000L Water Tank + Backup", category: "Plumbing", price: 25899, description: "Full water independence — tank, pump, filter, professional installation.", image: "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=600" }, 
    { id: 5, name: "CCTV 4-Camera System", category: "Security", price: 6500, description: "4x HD cameras, DVR, 1TB storage, remote viewing. Installation included.", image: "https://images.unsplash.com/photo-1557597774-9d273605dfa9?w=600", badge: "Includes Install" }, 
    { id: 6, name: "Electric Fence System", category: "Security", price: 4800, description: "Energiser, wire, and professional installation for residential plot.", image: "https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=600" }, 
    { id: 7, name: "Solar Geyser System", category: "Plumbing", price: 8500, description: "Cut geyser costs by up to 80%. Professional supply and installation.", image: "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?w=600" }, 
    { id: 8, name: "5KW Complete Solar Kit", category: "Solar", price: 22500, description: "Inverter + battery + panels + installation. Everything included.", image: "https://images.unsplash.com/photo-1509391366360-2e959784a276?w=600", badge: "Best Value" }, 
  ], 
  testimonials: [ 
    { name: "Sipho M.", location: "Meyerton", stars: 5, text: "Best solar installation in the Vaal. Professional team, clean work. System has been running perfectly for 8 months.", service: "Solar Installation" }, 
    { name: "Annetjie V.", location: "Vanderbijlpark", stars: 5, text: "Called for a plumbing emergency and they were there within 2 hours. Fixed it quickly and the price was fair.", service: "Plumbing" }, 
    { name: "Riana K.", location: "JHB South", stars: 5, text: "Had them install CCTV and electric fencing. Very professional, neat work, and they explained everything clearly.", service: "Security" }, 
  ], 
} 
